baseURL = "https://michael-mckenna.com"
languageCode = "en-us"
title = "Michael McKenna"
themesDir = "themes"
theme = "hugo-theme-peripheral"
enableGitInfo = true
DefaultContentLanguage = "en"
disableKinds = ["term", "taxonomy"]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = 'github-dark'
    tabWidth = 4
  [markup.goldmark.extensions]
    footnote = true
  [markup.goldmark.renderer]
hardWraps = true

[Params.Peripheral]
    favicon = "favicon.png"
    dateFormat = "January 2, 2006"
    subtitle = "All my Keystrokes That's Fit to Print"
    location = "Auckland, New Zealand"

[Params.Peripheral.GitInfo]
    enabled = true
    repository = "https://github.com/myquay/michaelmckenna.com"
    abbreviatedHash = "{{AbbreviatedHash}}"
    hash = "{{Hash}}"
    subject = "{{Subject}}"
    branch = "main"

[Params.Peripheral.Obsolescence]
    enabled = true
    years = 3
    message = "This content is more than 3 years old. Please read this keeping its age in mind."

[Params.Peripheral.Series]
    enabled = true
    showToBeContinued = true

# Add additional social link entries underneath
[Social]
    github = "myquay"

[Params.Peripheral.IndieWeb]
	name = "Michael McKenna"
	website = "https://michael-mckenna.com"
    photo = "/images/site/45eb93e3-6a59-4a2e-a16a-4dbfafc1a531.jpg"
    bio = "//TODO: Write short bio"
    auth = ["github"]
    authorization_endpoint = "https://indielogin.com/auth"
    token_endpoint = "https://indielogin.com/auth"

[mediaTypes]
    [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "rss"

[outputFormats.Atom]
    mediaType = "application/atom+xml"
    baseName = "atom"

[outputs] 
    section = ["HTML", "RSS", "Atom"]